spring:
  application:
    name: attendance-system
  profiles:
    active: dev # Si no se especifica perfil, arranca en modo desarrollo por defecto.
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

